import type { ComponentProps } from "react";
import { Ionicons } from "@expo/vector-icons";

export type CategoryIcon = ComponentProps<typeof Ionicons>["name"];

export const CATEGORY_ICONS: readonly CategoryIcon[] = [
  "restaurant-outline",
  "cart-outline",
  "basket-outline",
  "bus-outline",
  "car-outline",
  "bag-handle-outline",
  "receipt-outline",
  "game-controller-outline",
  "film-outline",
  "medical-outline",
  "medkit-outline",
  "school-outline",
  "home-outline",
  "airplane-outline",
  "paw-outline",
  "cafe-outline",
  "gift-outline",
  "fitness-outline",
  "phone-portrait-outline",
  "construct-outline",
  "people-outline",
  "briefcase-outline",
  "cash-outline",
  "arrow-down-circle-outline",
  "pie-chart-outline",
  "ellipsis-horizontal-outline",
  "fast-food-outline",
  "beer-outline",
  "wine-outline",
  "pizza-outline",
  "nutrition-outline",
  "ice-cream-outline",
  "bicycle-outline",
  "train-outline",
  "boat-outline",
  "subway-outline",
  "bed-outline",
  "business-outline",
  "hammer-outline",
  "leaf-outline",
  "water-outline",
  "flash-outline",
  "wifi-outline",
  "shirt-outline",
  "watch-outline",
  "laptop-outline",
  "hardware-chip-outline",
  "book-outline",
  "library-outline",
  "musical-notes-outline",
  "color-palette-outline",
  "football-outline",
  "tennisball-outline",
  "golf-outline",
  "bandage-outline",
  "heart-outline",
  "pulse-outline",
  "happy-outline",
  "cut-outline",
  "camera-outline",
  "print-outline",
  "diamond-outline",
  "flower-outline",
  "globe-outline",
  "location-outline",
  "map-outline",
  "key-outline",
  "lock-closed-outline",
  "shield-checkmark-outline",
  "wallet-outline",
  "card-outline",
];

export const CATEGORY_COLORS = [
  "#9A6BFF",
  "#8254E8",
  "#D6C0FF",
  "#0284C7",
  "#2563EB",
  "#4F46E5",
  "#7C3AED",
  "#9333EA",
  "#DB2777",
  "#DC2626",
  "#EA580C",
  "#D97706",
  "#475569",
  "#64748B",
  "#46D9A0",
  "#FF7B72",
  "#F4B860",
  "#66A3FF",
] as const;

export type CategoryColor = (typeof CATEGORY_COLORS)[number];
